export const COLOR_BACKGROUND = '#21303d';

export const SIZE_VIEWBOX_WIDTH = 3000;
export const SIZE_VIEWBOX_HEIGHT = SIZE_VIEWBOX_WIDTH * (4/3);
export const SIZE_RENDER_WIDTH = 600;
export const SIZE_RENDER_HEIGHT = SIZE_RENDER_WIDTH * (4/3);
export const SIZE_HEXAGON_RADIUS = 200;
